[project]
name = "stem-player-backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "numpy",
    "demucs",
    "torch",
    "torchaudio",
    "python-multipart",
    "websockets",
    "yt-dlp",
    "librosa",
    "matplotlib",
]

[project.optional-dependencies]
dev = ["pyinstaller"]

[tool.setuptools.packages.find]
include = ["app*"]
